<script type="text/javascript">
    $(document).ready(function(){
        // predicates stuff
        $(".predicates").change(function(){
            $("#all-predicates").attr('checked', false);
        });
        $("#all-predicates").change(function(){
            if($(this).attr("checked")){
                $(".predicates").each(function(){
                    $(this).attr("checked", false);
                });
            }
        });
        
        // languages stuff
        $(".languages").change(function(){
            $("#all-languages").attr('checked', false);
        });
        $("#all-languages").change(function(){
            if($(this).attr("checked")){
                $(".languages").each(function(){
                    $(this).attr("checked", false);
                });
            }
        });
    });
</script>

<!-- OPTIONS TABLE -->
<table>
<tr>
    <th>Predicates</th>
    <th>Languages</th>
</tr>
<tr>
    <td>
        <?php 
        $i = 0;
        foreach ($this->predicates as $predicate) { ?>
        <input type="checkbox" class="predicates" id="<?php echo $predicate; ?>">
        <a class="hasMenu" style="text-decoration:none;"
                                about="<?php echo $predicate; ?>"
                                href="<?php 
                                    $url = new OntoWiki_Url(array('route' => 'properties'), array('r'));
                                    $url->setParam('r', $predicate , true);
                                echo (string) $url ; ?>" >
                        <?php echo $this->titleHelper->getTitle($predicate, $this->locale); ?> 
        </a><br/>
        <?php
            $i++;
        } ?>
        <input type="radio" id="all-predicates" checked="true"> All predicates
    </td>
    <td>
        <?php 
        foreach ($this->languages as $key => $language) { ?>
            <input type="checkbox" class="languages" id="<?php echo $language->code; ?>"> <?php echo $language->label; ?> 
            <br/>
        <?php } ?>
        <input type="radio" id="all-languages" checked="true"> All languages
    </td>
</tr>
<tr>
    <td colspan="2" style="text-align:right;">
        <button value="OK">OK</button>
    </td>
</tr>
<!-- OPTIONS TABLE END -->
</table>

<?php foreach ($this->resources as $resource => $values) : ?>
<table style ="padding:0px;margin-top:1em; border-top:1px dotted #ababab; background-color:#ededed;width:100% ">
    <tr>
        <th style ="padding:0.2em; padding-left:1em; border-bottom:1px dotted #ababab; background-color:#dcdcdc " colspan="2">
            <a class="hasMenu" style="text-decoration:none;"
                                    about="<?php echo $resource; ?>"
                                    href="<?php
                                        $url = new OntoWiki_Url(array('route' => 'properties'), array('r'));
                                        $url->setParam('r', $resource , true);
                                    echo (string) $url ; ?>" >
                <?php echo $this->titleHelper->getTitle($resource, $this->locale); ?>
            </a>
        </th>
    </tr>

   <?php foreach ($values as $predicate => $objects) : ?>
    <tr >
        <td style ="padding:0.2em; padding-left:2em; border-bottom:1px dotted #ababab; background-color:#efefef " colspan="2">
            <a class="hasMenu" style="text-decoration:none;"
                                    about="<?php echo $predicate; ?>"
                                    href="<?php
                                        $url = new OntoWiki_Url(array('route' => 'properties'), array('r'));
                                        $url->setParam('r', $predicate , true);
                                    echo (string) $url ; ?>" >
                <?php echo $this->titleHelper->getTitle($predicate, $this->locale); ?>
            </a>
        </td>
    </tr>
       <?php foreach ($objects as $object) : ?>
        <tr style ="background-color:#fff " >
            <td style ="padding:0.2em; padding-left:3em;">
                <?php echo $object['lang'] ?>
            </td>
            <td>
                <input type="text" value="<?php echo $object['value'] ?>" size="100">
            </td>

        </tr>
        <?php endforeach ?>




   <?php endforeach ?>



</table>
<?php endforeach ?>
