<?php 
$i = 0;
foreach ($this->predicates as $predicate)
{
?>
<input type="checkbox" name="predicates" id="<?php echo $predicate; ?>">
<a class="hasMenu" style="text-decoration:none;"
                        about="<?php echo $predicate; ?>"
                        href="<?php 
                            $url = new OntoWiki_Url(array('route' => 'properties'), array('r'));
                            $url->setParam('r', $predicate , true);
                        echo (string) $url ; ?>" >
                <?php echo $this->titleHelper->getTitle($predicate, $this->locale); ?> 
</a><br/>
<?php
    $i++;
}
?>
<input type="radio" name="all-predicates"> All predicates
